export interface ExperiencePlace {
  id: string;
  name: string;
  area: string;
  description: string;
  priceRange: '₹' | '₹₹' | '₹₹₹' | '₹₹₹₹';
  tags: string[];
}

export interface ExperienceCategory {
  id: string;
  label: string;
  emoji: string;
  tagline: string;
  color: string;
  borderColor: string;
  textColor: string;
  places: ExperiencePlace[];
}

export const EXPERIENCE_CATEGORIES: ExperienceCategory[] = [
  {
    id: 'dinner',
    label: 'Fine Dining',
    emoji: '🍽️',
    tagline: 'Upscale restaurants for a memorable evening',
    color: 'rgba(245, 158, 11, 0.08)',
    borderColor: 'rgba(245, 158, 11, 0.18)',
    textColor: '#F59E0B',
    places: [
      {
        id: 'd1',
        name: 'Indian Accent',
        area: 'Lodi Estate, New Delhi',
        description: 'Award-winning modern Indian cuisine in a stunning heritage bungalow. Consistently ranked among Asia\'s best.',
        priceRange: '₹₹₹₹',
        tags: ['Fine Dining', 'Modern Indian', 'Award Winning'],
      },
      {
        id: 'd2',
        name: 'Bukhara',
        area: 'ITC Maurya, Chanakyapuri',
        description: 'Legendary NWFP frontier cuisine with a 45-year legacy. Known for the iconic Dal Bukhara.',
        priceRange: '₹₹₹₹',
        tags: ['NWFP Cuisine', 'Iconic', 'Traditional'],
      },
      {
        id: 'd3',
        name: 'Farzi Café',
        area: 'Cyber Hub, Gurgaon',
        description: 'Progressive Indian food with theatrical presentation and excellent craft cocktails.',
        priceRange: '₹₹₹',
        tags: ['Progressive Indian', 'Cocktails', 'Trendy'],
      },
      {
        id: 'd4',
        name: 'Smoke House Deli',
        area: 'Khan Market, New Delhi',
        description: 'European-inspired bistro with a warm, laid-back upscale vibe. Great for long dinners.',
        priceRange: '₹₹₹',
        tags: ['Continental', 'Bistro', 'Cozy'],
      },
      {
        id: 'd5',
        name: 'Lavaash by Saby',
        area: 'Bikaji Cama Place, New Delhi',
        description: 'Indo-Armenian cuisine by Chef Sabyasachi — one of Delhi\'s most unique dining experiences.',
        priceRange: '₹₹₹',
        tags: ['Unique', 'Chef\'s Table', 'Cocktails'],
      },
    ],
  },
  {
    id: 'coffee',
    label: 'Coffee Date',
    emoji: '☕',
    tagline: 'Great cafes for even better conversations',
    color: 'rgba(234, 88, 12, 0.08)',
    borderColor: 'rgba(234, 88, 12, 0.18)',
    textColor: '#EA580C',
    places: [
      {
        id: 'c1',
        name: 'Blue Tokai Coffee',
        area: 'Lodhi Colony, New Delhi',
        description: 'Delhi\'s favourite specialty roasters — warm, unhurried, with exceptional single-origin brews.',
        priceRange: '₹₹',
        tags: ['Specialty Coffee', 'Cozy', 'Indie'],
      },
      {
        id: 'c2',
        name: 'Perch Wine & Coffee Bar',
        area: 'Khan Market, New Delhi',
        description: 'Multi-level café with rooftop seating, a stunning wine menu, and excellent coffee.',
        priceRange: '₹₹₹',
        tags: ['Wine', 'Coffee', 'Rooftop'],
      },
      {
        id: 'c3',
        name: 'Digboi Café',
        area: 'Connaught Place, New Delhi',
        description: 'Artisan brews with an indie spirit in the heart of CP — great for a relaxed afternoon.',
        priceRange: '₹₹',
        tags: ['Artisan', 'Books', 'Chill'],
      },
      {
        id: 'c4',
        name: 'PCO Bar',
        area: 'Lodhi Road, New Delhi',
        description: 'Hidden speakeasy-style bar — excellent cocktails and coffee in an intimate, low-lit setting.',
        priceRange: '₹₹₹',
        tags: ['Speakeasy', 'Hidden Gem', 'Intimate'],
      },
      {
        id: 'c5',
        name: 'The Brew Room',
        area: 'Greater Kailash-I, New Delhi',
        description: 'Friendly neighbourhood café perfect for long conversations over great coffee.',
        priceRange: '₹₹',
        tags: ['Neighbourhood', 'Coffee', 'Relaxed'],
      },
    ],
  },
  {
    id: 'art-exhibition',
    label: 'Art Exhibition',
    emoji: '🎨',
    tagline: 'Galleries and exhibitions worth exploring',
    color: 'rgba(139, 92, 246, 0.08)',
    borderColor: 'rgba(139, 92, 246, 0.18)',
    textColor: '#8B5CF6',
    places: [
      {
        id: 'a1',
        name: 'National Gallery of Modern Art',
        area: 'India Gate, New Delhi',
        description: 'India\'s premier modern art museum — a stunning permanent collection plus rotating international shows.',
        priceRange: '₹',
        tags: ['Modern Art', 'Museum', 'Heritage'],
      },
      {
        id: 'a2',
        name: 'Kiran Nadar Museum of Art',
        area: 'Saket, New Delhi',
        description: 'World-class contemporary and modern Indian art in a beautiful space. Free entry.',
        priceRange: '₹',
        tags: ['Contemporary', 'Free Entry', 'Must Visit'],
      },
      {
        id: 'a3',
        name: 'Bikaner House',
        area: 'India Gate, New Delhi',
        description: 'Beautifully restored heritage palace hosting rotating cultural exhibitions and art shows.',
        priceRange: '₹₹',
        tags: ['Heritage', 'Rotating Shows', 'Architecture'],
      },
      {
        id: 'a4',
        name: 'India Habitat Centre',
        area: 'Lodhi Road, New Delhi',
        description: 'Cultural hub with ongoing art exhibitions, film screenings and evening performances.',
        priceRange: '₹',
        tags: ['Cultural Hub', 'Film', 'Events'],
      },
      {
        id: 'a5',
        name: 'Nature Morte Gallery',
        area: 'Neeti Bagh, New Delhi',
        description: 'Cutting-edge contemporary art — one of Asia\'s most respected private galleries.',
        priceRange: '₹',
        tags: ['Contemporary', 'Gallery', 'Prestigious'],
      },
    ],
  },
  {
    id: 'horse-riding',
    label: 'Horse Riding',
    emoji: '🐴',
    tagline: 'Equestrian experiences near Delhi',
    color: 'rgba(202, 138, 4, 0.08)',
    borderColor: 'rgba(202, 138, 4, 0.18)',
    textColor: '#CA8A04',
    places: [
      {
        id: 'h1',
        name: 'Delhi Riding Club',
        area: 'Safdarjung, New Delhi',
        description: 'Delhi\'s oldest and most storied riding club — professional lessons and scenic trail rides.',
        priceRange: '₹₹₹',
        tags: ['Historic', 'Lessons', 'Trail Rides'],
      },
      {
        id: 'h2',
        name: 'Aravalli Stables',
        area: 'Gurgaon',
        description: 'Scenic trail rides through the Aravalli hills — welcoming to first-timers and regulars alike.',
        priceRange: '₹₹₹',
        tags: ['Trail Rides', 'Beginners Welcome', 'Scenic'],
      },
      {
        id: 'h3',
        name: 'Polo Heritage Farm',
        area: 'Manesar, Haryana',
        description: 'Learn polo or take a countryside ride at this premium equestrian estate — unforgettable.',
        priceRange: '₹₹₹₹',
        tags: ['Polo', 'Premium', 'Countryside'],
      },
      {
        id: 'h4',
        name: 'Equestrian India',
        area: 'Noida',
        description: 'Structured riding programs for all levels — great if you\'ve never been on a horse.',
        priceRange: '₹₹₹',
        tags: ['All Levels', 'Structured', 'First-timers'],
      },
    ],
  },
  {
    id: 'live-music',
    label: 'Live Music',
    emoji: '🎵',
    tagline: "Delhi's best live music venues",
    color: 'rgba(168, 85, 247, 0.08)',
    borderColor: 'rgba(168, 85, 247, 0.18)',
    textColor: '#A855F7',
    places: [
      {
        id: 'lm1',
        name: 'Piano Man Jazz Club',
        area: 'Safdarjung Enclave, New Delhi',
        description: 'Delhi\'s most intimate jazz club — arguably the best live music experience in the city.',
        priceRange: '₹₹₹',
        tags: ['Jazz', 'Intimate', 'Must Visit'],
      },
      {
        id: 'lm2',
        name: 'Hard Rock Café',
        area: 'Connaught Place, New Delhi',
        description: 'Iconic live music venue with rock and pop performances every weekend.',
        priceRange: '₹₹₹',
        tags: ['Rock', 'Pop', 'Iconic'],
      },
      {
        id: 'lm3',
        name: 'Depot 48',
        area: 'Cyber Hub, Gurgaon',
        description: 'Live bands, craft beer and a great crowd — Gurgaon\'s go-to live music destination.',
        priceRange: '₹₹₹',
        tags: ['Live Bands', 'Craft Beer', 'Gurgaon'],
      },
      {
        id: 'lm4',
        name: 'The Klavierstück',
        area: 'Sultanpur, Delhi',
        description: 'Eclectic acoustic and classical performances in a uniquely intimate setting.',
        priceRange: '₹₹₹',
        tags: ['Classical', 'Acoustic', 'Unique'],
      },
    ],
  },
  {
    id: 'comedy',
    label: 'Comedy Night',
    emoji: '🎭',
    tagline: 'Stand-up shows and open mics',
    color: 'rgba(236, 72, 153, 0.08)',
    borderColor: 'rgba(236, 72, 153, 0.18)',
    textColor: '#EC4899',
    places: [
      {
        id: 'cm1',
        name: 'Canvas Laugh Club',
        area: 'Cyber Hub, Gurgaon',
        description: "Delhi-NCR's most popular dedicated stand-up comedy venue with regular shows.",
        priceRange: '₹₹₹',
        tags: ['Stand-up', 'Regular Shows', 'Popular'],
      },
      {
        id: 'cm2',
        name: 'The Comedy Factory',
        area: 'Various Venues, Delhi',
        description: 'Touring comedy shows featuring India\'s top comics — check for upcoming dates.',
        priceRange: '₹₹₹',
        tags: ['Top Comics', 'Touring Shows'],
      },
      {
        id: 'cm3',
        name: 'Social, Hauz Khas',
        area: 'Hauz Khas Village, New Delhi',
        description: 'Lively open mics and comedy nights in a buzzing atmosphere with great drinks.',
        priceRange: '₹₹',
        tags: ['Open Mic', 'Casual', 'Fun'],
      },
    ],
  },
  {
    id: 'outdoor',
    label: 'Outdoor Walk',
    emoji: '🌿',
    tagline: 'Nature trails and heritage walks',
    color: 'rgba(34, 197, 94, 0.08)',
    borderColor: 'rgba(34, 197, 94, 0.18)',
    textColor: '#22C55E',
    places: [
      {
        id: 'o1',
        name: 'Lodhi Garden',
        area: 'Lodhi Colony, New Delhi',
        description: 'Beautiful Mughal-era tombs set in 90 acres of manicured gardens — perfect for a sunset stroll.',
        priceRange: '₹',
        tags: ['Heritage', 'Greenery', 'Photography'],
      },
      {
        id: 'o2',
        name: 'Garden of Five Senses',
        area: 'Saket, New Delhi',
        description: 'Uniquely designed sensory garden — stunning at sunset with great photo opportunities.',
        priceRange: '₹',
        tags: ['Garden', 'Sunset', 'Peaceful'],
      },
      {
        id: 'o3',
        name: 'Aravalli Biodiversity Park',
        area: 'Vasant Vihar, New Delhi',
        description: 'Urban forest with walking trails and diverse flora. Free entry, surprisingly peaceful.',
        priceRange: '₹',
        tags: ['Nature', 'Free', 'Birding'],
      },
      {
        id: 'o4',
        name: 'Qutub Minar Complex',
        area: 'Mehrauli, New Delhi',
        description: 'A UNESCO World Heritage site — perfect for an architectural evening walk.',
        priceRange: '₹₹',
        tags: ['UNESCO', 'Architecture', 'History'],
      },
    ],
  },
  {
    id: 'arcade',
    label: 'Gaming & Fun',
    emoji: '🎮',
    tagline: 'Arcades, VR and escape rooms',
    color: 'rgba(6, 182, 212, 0.08)',
    borderColor: 'rgba(6, 182, 212, 0.18)',
    textColor: '#06B6D4',
    places: [
      {
        id: 'g1',
        name: 'Smaaash',
        area: 'Select Citywalk, Saket',
        description: "Delhi's best entertainment centre — VR, cricket simulator, bowling and more under one roof.",
        priceRange: '₹₹₹',
        tags: ['VR', 'Cricket Simulator', 'Bowling'],
      },
      {
        id: 'g2',
        name: 'The Breakout',
        area: 'Sector 29, Gurgaon',
        description: 'Immersive escape room experiences — perfect for a thrilling, unpredictable evening.',
        priceRange: '₹₹₹',
        tags: ['Escape Room', 'Thriller', 'Team'],
      },
      {
        id: 'g3',
        name: 'Fun Republic',
        area: 'Ansal Plaza, New Delhi',
        description: 'Arcade games, bowling and entertainment under one roof — great for a casual fun evening.',
        priceRange: '₹₹',
        tags: ['Arcade', 'Bowling', 'Fun'],
      },
    ],
  },
];
